source "https://rubygems.org"

# main
gem 'sinatra', :require => 'sinatra/base'

# db
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'

# testing
group :development, :test do
  gem 'cucumber-sinatra'
end
